docker_image: &docker_image
  docker:
    - image: circleci/node:4.8.2

version: 2
jobs:
  build:
    machine: true
    #<<: *docker_image
    steps:
      - checkout # check out the code in the project directory
      # - run: echo "hello ${CIRCLE_BUILD_NUM}" # run the `echo` command
      # - run: echo "hello ${TEST_CI}" # run the `echo` command
      # - run: echo "hello ${DOCKER_HUB_USER} ${DOCKER_HUB_PASSWORD}" # run the `echo` command
      # - run: docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD} # run the `echo` command
      - echo "hello ci"
      - ssh snaplogic@175.176.223.220
      - ls
  # build2:
  #   docker: # use the docker executor type; machine and macos executors are also supported
  #     - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
  #   branches:
  #     only:
  #       - master
  #       - /development/
  #   steps:
  #     - checkout # check out the code in the project directory
  #     - run: echo "hello world" # run the `echo` command
  #     - run: echo "hello world agail" # run the `echo` command

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - development
